import { CATEGORY_TYPE } from "./category.js";

export const ASSET_GRAPHQL_TYPE = {
  BASE: "Asset",
  INVESTMENT: "InvestmentAsset",
  OPERATING: "OperatingAsset",
  DUAL_PURPOSE: "DualPurposeAsset",
};

export const CATEGORY_ASSET_GRAPHQL_TYPE = {
  [CATEGORY_TYPE.INVESTING]: ASSET_GRAPHQL_TYPE.INVESTMENT,
  [CATEGORY_TYPE.OPERATING]: ASSET_GRAPHQL_TYPE.OPERATING,
  [CATEGORY_TYPE.DUAL_PURPOSE]: ASSET_GRAPHQL_TYPE.DUAL_PURPOSE,
};
